In [1]:
import pandas as pd
import numpy as np
import os
import re

In [2]:
file_1 = "Resources/2022-College-Guide-Main-Rankings-clear.csv"

In [ ]:
import urllib.request
rawdata = urllib.request.urlopen('https://washingtonmonthly.com/wp-content/uploads/2022/08/2022-College-Guide-Main-Rankings.xlsx').read()
import chardet
chardet.detect(rawdata)

In [3]:
data_df = pd.read_csv(file_1)

In [4]:
data_df.head()

,UnitID,Rank,Name,8-year graduation rate,Graduation rate rank,"Predicted graduation rate based on % of Pell recipients, incoming SATs, etc.",Graduation rate performance rank,Pell/non-Pell graduation gap,Pell graduation gap rank,Number of Pell graduates,...,% of federal work-study funds spent on service,% of federal work-study funds spent on service rank,Earns Carnegie Community Engagement Classification?,Voting engagement points,% of grads with service-oriented majors,Service-oriented majors rank,Social mobility rank,Research rank,Service rank,Unnamed: 40
0,243744,1,Stanford University (CA),0.963302,6,0.949654,187,-0.021703,46,260.6667,...,0.290903,10,NO,3,0.068361,401,3,2,187,NaN
1,215062,2,University of Pennsylvania (PA),0.964294,5,0.938620,149,-0.041917,104,376.6667,...,0.160573,71,YES,6,0.246743,209,2,9,40,NaN
2,166683,3,MA Institute of Technology (MA),0.950971,10,0.990213,334,-0.032985,72,182.6667,...,0.065477,332,NO,2,0.000000,436,5,1,324,NaN
3,186131,4,Princeton University (NJ),0.976861,2,0.947812,137,-0.052740,132,153.3333,...,0.064500,339,NO,6,0.000000,436,7,6,224,NaN
4,198419,5,Duke University (NC),0.954474,9,0.967952,267,-0.014278,36,231.6667,...,0.089523,224,YES,5,0.170164,305,12,15,20,NaN

In [5]:
data2_df = data_df.drop(columns = ["Unnamed: 40"])

In [7]:
data2_df.head()

,UnitID,Rank,Name,8-year graduation rate,Graduation rate rank,"Predicted graduation rate based on % of Pell recipients, incoming SATs, etc.",Graduation rate performance rank,Pell/non-Pell graduation gap,Pell graduation gap rank,Number of Pell graduates,...,ROTC rank,% of federal work-study funds spent on service,% of federal work-study funds spent on service rank,Earns Carnegie Community Engagement Classification?,Voting engagement points,% of grads with service-oriented majors,Service-oriented majors rank,Social mobility rank,Research rank,Service rank
0,243744,1,Stanford University (CA),0.963302,6,0.949654,187,-0.021703,46,260.6667,...,308,0.290903,10,NO,3,0.068361,401,3,2,187
1,215062,2,University of Pennsylvania (PA),0.964294,5,0.938620,149,-0.041917,104,376.6667,...,250,0.160573,71,YES,6,0.246743,209,2,9,40
2,166683,3,MA Institute of Technology (MA),0.950971,10,0.990213,334,-0.032985,72,182.6667,...,12,0.065477,332,NO,2,0.000000,436,5,1,324
3,186131,4,Princeton University (NJ),0.976861,2,0.947812,137,-0.052740,132,153.3333,...,34,0.064500,339,NO,6,0.000000,436,7,6,224
4,198419,5,Duke University (NC),0.954474,9,0.967952,267,-0.014278,36,231.6667,...,45,0.089523,224,YES,5,0.170164,305,12,15,20

In [8]:
data2_df.dtypes

UnitID                                                                            int64
Rank                                                                              int64
Name                                                                             object
8-year graduation rate                                                          float64
Graduation rate rank                                                              int64
Predicted graduation rate based on % of Pell recipients, incoming SATs, etc.    float64
Graduation rate performance rank                                                  int64
Pell/non-Pell graduation gap                                                    float64
Pell graduation gap rank                                                          int64
Number of Pell graduates                                                        float64
Actual vs. predicted Pell enrollment                                            float64
Pell performance rank                                                             int64
Median earnings 10 years after entering college                                   int64
Predicted median earnings 10 years after entering college                       float64
Earnings performance rank                                                         int64
Net price of attendance for families below $75,000 income                       float64
Net price rank                                                                    int64
% of loan principal remaining 5 years later                                     float64
Repayment rank                                                                    int64
Predicted principal remaining                                                   float64
Repayment rate performance rank                                                   int64
Research expenditures, in millions                                              float64
Research expenditures rank                                                        int64
Bachelor's to PhD rank                                                            int64
Science & engineering PhDs awarded                                              float64
Science & engineering PhDs rank                                                   int64
Faculty receiving significant awards                                            float64
Faculty in National Academies                                                   float64
Faculty accolades rank                                                            int64
AmeriCorps/Peace Corps rank                                                       int64
ROTC rank                                                                         int64
% of federal work-study funds spent on service                                  float64
% of federal work-study funds spent on service rank                               int64
Earns Carnegie Community Engagement Classification?                              object
Voting engagement points                                                          int64
% of grads with service-oriented majors                                         float64
Service-oriented majors rank                                                      int64
Social mobility rank                                                              int64
Research rank                                                                     int64
Service rank                                                                      int64
dtype: object

In [9]:
data2_df.count()

UnitID                                                                          442
Rank                                                                            442
Name                                                                            442
8-year graduation rate                                                          442
Graduation rate rank                                                            442
Predicted graduation rate based on % of Pell recipients, incoming SATs, etc.    442
Graduation rate performance rank                                                442
Pell/non-Pell graduation gap                                                    442
Pell graduation gap rank                                                        442
Number of Pell graduates                                                        442
Actual vs. predicted Pell enrollment                                            442
Pell performance rank                                                           442
Median earnings 10 years after entering college                                 442
Predicted median earnings 10 years after entering college                       442
Earnings performance rank                                                       442
Net price of attendance for families below $75,000 income                       442
Net price rank                                                                  442
% of loan principal remaining 5 years later                                     442
Repayment rank                                                                  442
Predicted principal remaining                                                   442
Repayment rate performance rank                                                 442
Research expenditures, in millions                                              442
Research expenditures rank                                                      442
Bachelor's to PhD rank                                                          442
Science & engineering PhDs awarded                                              442
Science & engineering PhDs rank                                                 442
Faculty receiving significant awards                                            442
Faculty in National Academies                                                   442
Faculty accolades rank                                                          442
AmeriCorps/Peace Corps rank                                                     442
ROTC rank                                                                       442
% of federal work-study funds spent on service                                  442
% of federal work-study funds spent on service rank                             442
Earns Carnegie Community Engagement Classification?                             442
Voting engagement points                                                        442
% of grads with service-oriented majors                                         442
Service-oriented majors rank                                                    442
Social mobility rank                                                            442
Research rank                                                                   442
Service rank                                                                    442
dtype: int64

In [10]:
data2_df.describe()

,UnitID,Rank,8-year graduation rate,Graduation rate rank,"Predicted graduation rate based on % of Pell recipients, incoming SATs, etc.",Graduation rate performance rank,Pell/non-Pell graduation gap,Pell graduation gap rank,Number of Pell graduates,Actual vs. predicted Pell enrollment,...,AmeriCorps/Peace Corps rank,ROTC rank,% of federal work-study funds spent on service,% of federal work-study funds spent on service rank,Voting engagement points,% of grads with service-oriented majors,Service-oriented majors rank,Social mobility rank,Research rank,Service rank
count,442.000000,442.000000,442.000000,442.000000,442.000000,442.000000,442.000000,442.000000,442.000000,4.420000e+02,...,442.000000,442.000000,442.000000,442.000000,442.000000,442.000000,442.000000,442.000000,442.000000,442.000000
mean,184512.868778,221.500000,0.642714,221.500000,0.642629,221.500000,-0.095178,221.500000,741.368021,-1.583710e-09,...,221.398190,218.728507,0.106425,221.262443,2.547511,0.270311,221.452489,221.500000,221.452489,221.500000
std,58768.666269,127.738666,0.158808,127.738666,0.144934,127.738666,0.077926,127.738666,850.725238,7.763040e-02,...,127.567028,123.551704,0.065754,127.343925,2.381668,0.175734,127.657861,127.738666,127.657861,127.738666
min,100663.000000,1.000000,0.080237,1.000000,0.220492,1.000000,-0.500000,1.000000,23.000000,-3.093742e-01,...,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,145747.000000,111.250000,0.529251,111.250000,0.552245,111.250000,-0.141566,111.250000,196.916675,-4.798322e-02,...,111.250000,111.250000,0.065488,111.250000,0.000000,0.150001,111.250000,111.250000,111.250000,111.250000
50%,180745.500000,221.500000,0.629700,221.500000,0.624093,221.500000,-0.092755,221.500000,495.166650,-3.763300e-03,...,221.500000,221.500000,0.089997,221.500000,3.000000,0.229810,221.500000,221.500000,221.500000,221.500000
75%,216359.250000,331.750000,0.754697,331.750000,0.728486,331.750000,-0.045979,331.750000,972.499975,4.414932e-02,...,331.750000,331.750000,0.130604,331.750000,5.000000,0.358887,331.750000,331.750000,331.750000,331.750000
max,495767.000000,442.000000,0.979428,442.000000,1.000000,442.000000,0.676191,442.000000,9068.333000,2.520086e-01,...,433.000000,393.000000,0.509211,428.000000,6.000000,0.902994,436.000000,442.000000,436.000000,442.000000

In [ ]:
#use groupby to get stats on... top 20 in service vs. top 20 in something else?
#use R for feature importance relative to rank
#use machine learning for feature importances 
#use machine learning for feature importances relative to items that are not rank 
#add lat/lng to dataset to plot in tableau